### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by BanCrash** [jonashertzman/PhotoMover2#3]
Hi, I downloaded the last release but I don't know how to use it to be honest, I've tried a couple things but the best I've got is an error that says "Copy failed. Value cannot be null (parameter path)". Is there any place where I can see how to use this properly?

Regards.

**Comment by BanCrash** [comment]
Ok, after more testing I've finally learned how to use. Thanks for this!

**Comment by jonashertzman** [comment]
Yes I agree this needs a little bit more love when it comes to usability :)

Do you have any idea what I could add to the dialog to make this more understandable?

Would an example in the help popup be enough?

**Comment by BanCrash** [comment]
> Yes I agree this needs a little bit more love when it comes to usability :)
> 
> Do you have any idea what I could add to the dialog to make this more understandable?
> 
> Would an example in the help popup be enough?

Yep, I think that when you realize how to use it it's not very difficult, so the example should be enough.
