### ISSUE TITLE
Add an option for removing from original folder after importing / command line support

### ISSUE THREAD

**Issue by BanCrash** [jonashertzman/PhotoMover2#4]
Hi again! After using it I have a couple of suggestions:

- Add an option to move photos instead of copying them. I want the photos to be removed from the original folder after imported to the new folder, since my idea for this program is to automatically reorganize the photos.
- Related to my idea of automatically reorganize the photos, having a simple command line support would let us to have a task that programatically reorganize the photos using cmd. So for example after log in on the user, Windows will execute a .bat file that have this order inside:

`PhotoMover.exe "E:\Photos"`. Since the importing filters are saved, it will simply execute first the "find files" command and after that, the "copy" command. If there is any error, it will simply skip these files as it happens on the GUI version. I personally don't need any error throwing in that case since I will easily know if the program failed or worked checking the original folder, which should be empty after the importing.

**Comment by jonashertzman** [comment]
Hi

I have now added the possibility to run the application in console mode when running the application with command line option `-c`

`PhotoMover.exe "E:\Photos" -c`

To delete files after import you can add option `-d`

You still need to run the application in window mode to configure the import, then the console application will use the same configuration.

I also added a few examples in the help panel of the configuration window to give a few hints how to configure the import.

**Comment by BanCrash** [comment]
Hi @jonashertzman , I just tested the new build. The examples are just perfect. About the new command line and the option to move the photos, it worked like a charm, however there is a minor issue. When the program ends, the command line doesn't get automatically close. Is there something that I'm doing wrong or that's the actual behaviour?

In any case nice job, thank you!!

**Comment by jonashertzman** [comment]
Hi.

Do you get the prompt that says "Press any key to continue"?  I added that on purpose to be able to see the output when starting an import from a shortcut.

Or are you getting this when executing from a command prompt? I just realized I'm getting this behavior to in Windows Command Prompt and in PowerShell but not in Bash for some reason...

**Comment by BanCrash** [comment]
> Hi.
> 
> Do you get the prompt that says "Press any key to continue"? I added that on purpose to be able to see the output when starting an import from a shortcut.
> 
> Or are you getting this when executing from a command prompt? I just realized I'm getting this behavior to in Windows Command Prompt and in PowerShell but not in Bash for some reason...

No, I opened from cmd directly and I don't get any message. When it ends it simply ends in standby until I press enter:

![imagen](https://user-images.githubusercontent.com/11770760/211860044-cb8cd97c-353b-44be-a7bc-06cc238beafb.png)

However I just created a .bat file and in that it just autoclose, which was my expected behaviour, so it's fine for me. I just have to make that bat to execute when login on Windows and that will be all for me.

Thanks again!

**Comment by BanCrash** [comment]
As I said I created a bat file and set up to start with Windows, and it's working like a charm, thank you so much!
