### ISSUE TITLE
Copy all files

### ISSUE THREAD

**Issue by dlmac** [jonashertzman/PhotoMover2#6]
Now that I have found all files and ready to copy. There is no way to select all. No way am I checking a box of 10, 000 rows one by one.

Can we get a select all button?

**Comment by BanCrash** [comment]
> Now that I have found all files and ready to copy. There is no way to select all. No way am I checking a box of 10, 000 rows one by one.
> 
> Can we get a select all button?

Hi, are you sure that your files match your filter? The files that match the filter are automatically selected in my case:
![imagen](https://user-images.githubusercontent.com/11770760/219971276-93d063a9-bb03-4757-92f7-fc938822d21a.png)

**Comment by jonashertzman** [comment]
All files specified in the import configuration will be checked by default when they are found unless they are duplicates. Status Ignored means that they do not match any import configuration. 

I made it this way where all files in the import folder are shown to give an indication that this folder also contains files not specified by the import configuration, to not give the illusion that everything is imported when it's not.

**Comment by dlmac** [comment]
I found my issue. I set the Library Root Directory to the Source and not where they are being moved/Copied to.
